name: Test Release

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test name'
        required: true
        default: 'test-release'
      branch:
        description: 'Branch to run on'
        required: true
        default: 'fix/release'

jobs:
  test-release:
    name: Test Release Process
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ toolchain
        run: |
          # Remove problematic Microsoft repository to avoid 421 Misdirected Request error
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update --allow-releaseinfo-change
          sudo apt-get install -y build-essential cmake ninja-build libboost-all-dev

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DUNILINK_ENABLE_INSTALL=ON \
            -DUNILINK_ENABLE_PKGCONFIG=ON \
            -DUNILINK_ENABLE_EXPORT_HEADER=ON

      - name: Build
        run: cmake --build build --config Release -- -v

      - name: Test
        run: cmake --build build --target test

      - name: Package
        run: |
          cd build
          cpack -B package -G TGZ
          ls -la package/

      - name: Show package contents
        run: |
          cd build/package
          tar -tzf unilink-*.tar.gz | head -20

      - name: Test package extraction
        run: |
          cd build/package
          mkdir -p test_extract
          tar -xzf unilink-*.tar.gz -C test_extract
          ls -la test_extract/

      - name: Summary
        run: |
          echo "## Test Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build: Success" >> $GITHUB_STEP_SUMMARY
          echo "✅ Tests: Passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Package: Created" >> $GITHUB_STEP_SUMMARY
          echo "📦 Package files:" >> $GITHUB_STEP_SUMMARY
          ls -la build/package/ >> $GITHUB_STEP_SUMMARY
